# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "impact-co2"
client_id = "a945e3134179506cbdd815c083b07f43"
application_url = "https://cafe-belief-themes-teaches.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cafe-belief-themes-teaches.trycloudflare.com/auth/callback",
  "https://cafe-belief-themes-teaches.trycloudflare.com/auth/shopify/callback",
  "https://cafe-belief-themes-teaches.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9d917803.myshopify.com"
